// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: objectLifetime.proto

package org.eclipse.imp.pdb.facts.tracking;

public final class TrackingProtocolBuffers {
  private TrackingProtocolBuffers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ObjectLifetimeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 tag = 1;
    /**
     * <code>required int64 tag = 1;</code>
     */
    boolean hasTag();
    /**
     * <code>required int64 tag = 1;</code>
     */
    long getTag();

    // required string digest = 2;
    /**
     * <code>required string digest = 2;</code>
     */
    boolean hasDigest();
    /**
     * <code>required string digest = 2;</code>
     */
    java.lang.String getDigest();
    /**
     * <code>required string digest = 2;</code>
     */
    com.google.protobuf.ByteString
        getDigestBytes();

    // required int64 ctorTime = 3;
    /**
     * <code>required int64 ctorTime = 3;</code>
     */
    boolean hasCtorTime();
    /**
     * <code>required int64 ctorTime = 3;</code>
     */
    long getCtorTime();

    // optional int64 dtorTime = 4;
    /**
     * <code>optional int64 dtorTime = 4;</code>
     */
    boolean hasDtorTime();
    /**
     * <code>optional int64 dtorTime = 4;</code>
     */
    long getDtorTime();

    // optional int64 measuredSizeInBytes = 5;
    /**
     * <code>optional int64 measuredSizeInBytes = 5;</code>
     */
    boolean hasMeasuredSizeInBytes();
    /**
     * <code>optional int64 measuredSizeInBytes = 5;</code>
     */
    long getMeasuredSizeInBytes();
  }
  /**
   * Protobuf type {@code ObjectLifetime}
   */
  public static final class ObjectLifetime extends
      com.google.protobuf.GeneratedMessage
      implements ObjectLifetimeOrBuilder {
    // Use ObjectLifetime.newBuilder() to construct.
    private ObjectLifetime(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ObjectLifetime(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ObjectLifetime defaultInstance;
    public static ObjectLifetime getDefaultInstance() {
      return defaultInstance;
    }

    public ObjectLifetime getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ObjectLifetime(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              tag_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              digest_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              ctorTime_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              dtorTime_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              measuredSizeInBytes_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.internal_static_ObjectLifetime_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.internal_static_ObjectLifetime_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime.class, org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime.Builder.class);
    }

    public static com.google.protobuf.Parser<ObjectLifetime> PARSER =
        new com.google.protobuf.AbstractParser<ObjectLifetime>() {
      public ObjectLifetime parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ObjectLifetime(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ObjectLifetime> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 tag = 1;
    public static final int TAG_FIELD_NUMBER = 1;
    private long tag_;
    /**
     * <code>required int64 tag = 1;</code>
     */
    public boolean hasTag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 tag = 1;</code>
     */
    public long getTag() {
      return tag_;
    }

    // required string digest = 2;
    public static final int DIGEST_FIELD_NUMBER = 2;
    private java.lang.Object digest_;
    /**
     * <code>required string digest = 2;</code>
     */
    public boolean hasDigest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string digest = 2;</code>
     */
    public java.lang.String getDigest() {
      java.lang.Object ref = digest_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          digest_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string digest = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDigestBytes() {
      java.lang.Object ref = digest_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        digest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 ctorTime = 3;
    public static final int CTORTIME_FIELD_NUMBER = 3;
    private long ctorTime_;
    /**
     * <code>required int64 ctorTime = 3;</code>
     */
    public boolean hasCtorTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 ctorTime = 3;</code>
     */
    public long getCtorTime() {
      return ctorTime_;
    }

    // optional int64 dtorTime = 4;
    public static final int DTORTIME_FIELD_NUMBER = 4;
    private long dtorTime_;
    /**
     * <code>optional int64 dtorTime = 4;</code>
     */
    public boolean hasDtorTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 dtorTime = 4;</code>
     */
    public long getDtorTime() {
      return dtorTime_;
    }

    // optional int64 measuredSizeInBytes = 5;
    public static final int MEASUREDSIZEINBYTES_FIELD_NUMBER = 5;
    private long measuredSizeInBytes_;
    /**
     * <code>optional int64 measuredSizeInBytes = 5;</code>
     */
    public boolean hasMeasuredSizeInBytes() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 measuredSizeInBytes = 5;</code>
     */
    public long getMeasuredSizeInBytes() {
      return measuredSizeInBytes_;
    }

    private void initFields() {
      tag_ = 0L;
      digest_ = "";
      ctorTime_ = 0L;
      dtorTime_ = 0L;
      measuredSizeInBytes_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDigest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCtorTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, tag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDigestBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, ctorTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, dtorTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, measuredSizeInBytes_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, tag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDigestBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, ctorTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, dtorTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, measuredSizeInBytes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ObjectLifetime}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.internal_static_ObjectLifetime_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.internal_static_ObjectLifetime_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime.class, org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime.Builder.class);
      }

      // Construct using org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tag_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        digest_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ctorTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        dtorTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        measuredSizeInBytes_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.internal_static_ObjectLifetime_descriptor;
      }

      public org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime getDefaultInstanceForType() {
        return org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime.getDefaultInstance();
      }

      public org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime build() {
        org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime buildPartial() {
        org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime result = new org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tag_ = tag_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.digest_ = digest_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ctorTime_ = ctorTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dtorTime_ = dtorTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.measuredSizeInBytes_ = measuredSizeInBytes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime) {
          return mergeFrom((org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime other) {
        if (other == org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime.getDefaultInstance()) return this;
        if (other.hasTag()) {
          setTag(other.getTag());
        }
        if (other.hasDigest()) {
          bitField0_ |= 0x00000002;
          digest_ = other.digest_;
          onChanged();
        }
        if (other.hasCtorTime()) {
          setCtorTime(other.getCtorTime());
        }
        if (other.hasDtorTime()) {
          setDtorTime(other.getDtorTime());
        }
        if (other.hasMeasuredSizeInBytes()) {
          setMeasuredSizeInBytes(other.getMeasuredSizeInBytes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTag()) {
          
          return false;
        }
        if (!hasDigest()) {
          
          return false;
        }
        if (!hasCtorTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.eclipse.imp.pdb.facts.tracking.TrackingProtocolBuffers.ObjectLifetime) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 tag = 1;
      private long tag_ ;
      /**
       * <code>required int64 tag = 1;</code>
       */
      public boolean hasTag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 tag = 1;</code>
       */
      public long getTag() {
        return tag_;
      }
      /**
       * <code>required int64 tag = 1;</code>
       */
      public Builder setTag(long value) {
        bitField0_ |= 0x00000001;
        tag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 tag = 1;</code>
       */
      public Builder clearTag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tag_ = 0L;
        onChanged();
        return this;
      }

      // required string digest = 2;
      private java.lang.Object digest_ = "";
      /**
       * <code>required string digest = 2;</code>
       */
      public boolean hasDigest() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string digest = 2;</code>
       */
      public java.lang.String getDigest() {
        java.lang.Object ref = digest_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          digest_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string digest = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDigestBytes() {
        java.lang.Object ref = digest_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          digest_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string digest = 2;</code>
       */
      public Builder setDigest(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        digest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string digest = 2;</code>
       */
      public Builder clearDigest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        digest_ = getDefaultInstance().getDigest();
        onChanged();
        return this;
      }
      /**
       * <code>required string digest = 2;</code>
       */
      public Builder setDigestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        digest_ = value;
        onChanged();
        return this;
      }

      // required int64 ctorTime = 3;
      private long ctorTime_ ;
      /**
       * <code>required int64 ctorTime = 3;</code>
       */
      public boolean hasCtorTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 ctorTime = 3;</code>
       */
      public long getCtorTime() {
        return ctorTime_;
      }
      /**
       * <code>required int64 ctorTime = 3;</code>
       */
      public Builder setCtorTime(long value) {
        bitField0_ |= 0x00000004;
        ctorTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ctorTime = 3;</code>
       */
      public Builder clearCtorTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ctorTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 dtorTime = 4;
      private long dtorTime_ ;
      /**
       * <code>optional int64 dtorTime = 4;</code>
       */
      public boolean hasDtorTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 dtorTime = 4;</code>
       */
      public long getDtorTime() {
        return dtorTime_;
      }
      /**
       * <code>optional int64 dtorTime = 4;</code>
       */
      public Builder setDtorTime(long value) {
        bitField0_ |= 0x00000008;
        dtorTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 dtorTime = 4;</code>
       */
      public Builder clearDtorTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dtorTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 measuredSizeInBytes = 5;
      private long measuredSizeInBytes_ ;
      /**
       * <code>optional int64 measuredSizeInBytes = 5;</code>
       */
      public boolean hasMeasuredSizeInBytes() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 measuredSizeInBytes = 5;</code>
       */
      public long getMeasuredSizeInBytes() {
        return measuredSizeInBytes_;
      }
      /**
       * <code>optional int64 measuredSizeInBytes = 5;</code>
       */
      public Builder setMeasuredSizeInBytes(long value) {
        bitField0_ |= 0x00000010;
        measuredSizeInBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 measuredSizeInBytes = 5;</code>
       */
      public Builder clearMeasuredSizeInBytes() {
        bitField0_ = (bitField0_ & ~0x00000010);
        measuredSizeInBytes_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ObjectLifetime)
    }

    static {
      defaultInstance = new ObjectLifetime(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ObjectLifetime)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ObjectLifetime_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ObjectLifetime_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024objectLifetime.proto\"n\n\016ObjectLifetime" +
      "\022\013\n\003tag\030\001 \002(\003\022\016\n\006digest\030\002 \002(\t\022\020\n\010ctorTim" +
      "e\030\003 \002(\003\022\020\n\010dtorTime\030\004 \001(\003\022\033\n\023measuredSiz" +
      "eInBytes\030\005 \001(\003B=\n\"org.eclipse.imp.pdb.fa" +
      "cts.trackingB\027TrackingProtocolBuffers"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ObjectLifetime_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ObjectLifetime_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ObjectLifetime_descriptor,
              new java.lang.String[] { "Tag", "Digest", "CtorTime", "DtorTime", "MeasuredSizeInBytes", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
